Implemented TanStack Query for api calls
Hugovs2000/React-Project pull request #1
Opened 2024-03-11 15:21 UTC by Hugovs2000

I am making use of TanStack query for my api calls to the comick.io api. The use of the calls have been tested in `MainContext.tsx` and is subject to change.

2024-03-11 19:35 UTC, Julianna-Venter approved these changes
I'm not super familiar with TanStack query yet, but from what I can see it looks good. Just have a second reviewer check it over as well. I would also recommend adding branch rules.

2024-03-11 19:35 UTC, Julianna-Venter commented on ChronicalFrames/src/models/topTrending.d.ts
> +}
You have lots of interfaces here and in other files, I know you are still in the process of adapting the code, but later on when you're done just make sure all of them are necessary and being used, and just remove those that aren't (otherwise it's good)

2024-03-11 20:27 UTC, Musa-Mabasa commented on ChronicalFrames/src/dom/MainContent/MainContent.tsx
> +          {topData ? (
For better UX, maybe use the `isLoading` property from useQuery instead of checking if `topData` is undefined

2024-03-11 20:31 UTC, Musa-Mabasa commented on ChronicalFrames/src/dom/MainContent/MainContent.tsx
> +          ) : null}
I assume you will change this `null` as you improve your UI to some loader component, which is fine. However I do not think merging a null component into main is advised.

2024-03-12 05:31 UTC, Hugovs2000 commented on ChronicalFrames/src/dom/MainContent/MainContent.tsx
> +          {topData ? (
Sure thing, this code was just used to test if the api calls work. Will implement it properly next time 😁

2024-03-12 05:32 UTC, Hugovs2000 commented on ChronicalFrames/src/dom/MainContent/MainContent.tsx
> +          ) : null}
Yes it will change, as the code was just used to test if the api calls work

2024-03-12 06:23 UTC, CharelMarais requested changes
Just a few notes and please change the ternary to a Logical AND

2024-03-12 06:23 UTC, CharelMarais commented on ChronicalFrames/src/dom/MainContent/MainContent.tsx
> +          {topData ? (
`isLoading` has been changed to `isPending` in tanstack v5 and `isInitialLoading` has been changed to `isLoading`

I would rather use `isSuccess` instead of `isLoading` as `isLoading` it will change to false on error or success

2024-03-12 06:23 UTC, CharelMarais commented on ChronicalFrames/src/models/topTrending.d.ts
> +}
I would say to keep all the interfaces so all the data for the api is mapped and the models are future proof

2024-03-12 06:23 UTC, CharelMarais commented on ChronicalFrames/src/dom/MainContent/MainContent.tsx
> +          ) : null}
Use `&&` and removed the `( )` & `: null` instead of using the Ternary Operator this will only display the code if the checked data is true no need for a false value.

2024-03-12 06:46 UTC, CharelMarais approved these changes
Looks good

2024-03-12 06:48 UTC, merged