Zustand feature
Hugovs2000/React-Project pull request #11
Opened 2024-03-29 11:05 UTC by Hugovs2000

Made use of Zustand to implement a continue reading function that takes the user to their last read manga chapter.
Also implemented a favourites feature where a user can favourite a manga on the manga's detail page and also view their favourite mangas by navigating to the favourites page from the hamburger menu. Slightly fixed some code here and there as well.

2024-03-29 19:19 UTC, Julianna-Venter approved these changes
Looks good to me, just carefully double check behaviour, especially with your useEffect and how data is being updated. I'd just spend some time trying to break it, just to make sure state is staying consistent. But I haven't seen any obvious weird behaviours, so well done!

2024-03-30 07:15 UTC, tanadendere approved these changes
This is looking good, well done!

2024-03-30 07:34 UTC, Musa-Mabasa commented on src/routes/__root.tsx
> +              lastReadPage?.[0].length > 0 &&
Safety check here: `lastReadPage?.[0]?.length`

2024-03-30 07:40 UTC, Musa-Mabasa commented on src/modules/SeeMorePage/components/SeeMoreSeasonal.tsx
> +              item?.md_covers?.[0].b2key && (
Safety check here as well.

2024-03-30 07:41 UTC, Musa-Mabasa requested changes
Everything looks good, just a few missing safety checks from my comments

2024-03-30 07:56 UTC, Hugovs2000 commented on src/routes/__root.tsx
> +              lastReadPage?.[0].length > 0 &&
Thank you 🙏🏻

2024-03-30 07:56 UTC, Hugovs2000 commented on src/modules/SeeMorePage/components/SeeMoreSeasonal.tsx
> +              item?.md_covers?.[0].b2key && (
Thank you 🙏🏻

2024-03-30 16:18 UTC, LesediMoko approved these changes
You put in a lot of good, hard work in this one. Super impressive 👏. Just minor comments regarding z-indices and conditional statements but all-in-all, amazing work Hugo 🏄🏽‍♂️

2024-03-30 16:18 UTC, LesediMoko commented on src/modules/ReadMangaPage/components/TopInfoBar.tsx
> +    <div className="h-10 fixed top-16 p-2 w-full flex items-center bg-emerald-700 rounded-b-md z-20">
would z-10 not be sufficient here?

2024-03-30 16:18 UTC, LesediMoko commented on src/state/state-service.ts
> +  persist(
Great use of persistence to keep the track of the LastRead and favourites 👏

2024-03-30 16:18 UTC, LesediMoko commented on src/modules/MangaDetailsPage/components/MangaHeader.tsx
> +    if (topData?.comic?.slug) {
I see that the logic should only evaluate if topData.comic.slug exists (without an else block). Maybe consider using a short circuit. i.e. ` topData?.comic?.slug && {//second if logic) `

2024-03-31 08:14 UTC, Musa-Mabasa approved these changes
Everything looks good 👍

2024-04-01 06:44 UTC, Hugovs2000 commented on src/modules/MangaDetailsPage/components/MangaHeader.tsx
> +    if (topData?.comic?.slug) {
Thank you 👍🏻

2024-04-01 06:49 UTC, Hugovs2000 commented on src/modules/ReadMangaPage/components/TopInfoBar.tsx
> +    <div className="h-10 fixed top-16 p-2 w-full flex items-center bg-emerald-700 rounded-b-md z-20">
I tried it, the chapter images scroll over the top info bar, only works with z-20. Thanks though

2024-04-01 06:54 UTC, merged