Landing feature
Hugovs2000/React-Project pull request #4
Opened 2024-03-14 20:23 UTC by Hugovs2000

Finished up implementing the landing page that displays trending manga, latest updates, top 10 and seasonal manga. Note that the see mare buttons are not yet set to route just yet.

2024-03-15 07:03 UTC, yanevdw approved these changes
Nicely done.

2024-03-15 08:18 UTC, Julianna-Venter approved these changes
Some minor comments worth looking into as you progress, but looks good.

2024-03-15 08:18 UTC, Julianna-Venter commented on src/components/homePage/seasonalComponent.tsx
> +    return <>Not Found</>;
might want to look into a better way to handle these errors (error page, styled component, etc.), but that can come later

2024-03-15 08:18 UTC, Julianna-Venter commented on src/components/homePage/topTenComponent.tsx
> +              className="indicator min-w-fit md:max-w-full md:min-w-[400px]"
could convert `px` to `rem` (this would be `25rem`, there is an online pixel to rem converter that I use for this)
Just check all your instances and if they could/should be changed

2024-03-15 08:18 UTC, Julianna-Venter commented on src/components/homePage/seasonalComponent.tsx
> +    return <>Not Found</>;
You have quite a few of these throughout, I would recommend making a styled component. I'm not going to comment on all of them, this is up to your preference.

2024-03-15 08:18 UTC, Julianna-Venter commented on src/routes/__root.tsx
> +      <Navbar className="fixed z-[999] navbar bg-zinc-900 flex flex-shrink-0" />
`z-[999]` seems a bit excessive, highest preset value in tailwind is `z-50` which I would rather recommend using if you do not have other elements on the z-axis. This also seems a bit strange since this is your root element. Maybe just take a look at how you are positioning elements on the z-axis, unless this `z-[999]` was done for a specific reason?

2024-03-15 08:39 UTC, theadley requested changes
Renaming components to PascalCase in alignment with React best practices.
I feel like you can make some of these reusable components so that if any look like the same, make them actually the same.

2024-03-15 08:39 UTC, theadley commented on src/components/homePage/homeComponent.tsx
> +    <>
Don't need a frag if you return one node (the div)

2024-03-15 08:39 UTC, theadley commented on src/components/homePage/latestUpdates.tsx
> +        "https://meo3.comick.pictures/" + item.md_comics.md_covers[0].b2key
Check if it exists first, please. You can do this by filtering before mapping.
`latestUpdatesData?.filter(item => !!item.md_comics?.md_covers?.[0]?.b2key)?.slice(0, 15).map((item) => {...})`

2024-03-15 08:39 UTC, theadley commented on src/components/homePage/latestUpdates.tsx
> +        <button className="text-blue-400">See more</button>
Assuming these will be linked later with a different branch?

2024-03-15 08:39 UTC, theadley commented on src/components/homePage/latestUpdates.tsx
> +        {latestUpdatesData.slice(0, 15).map((item, index: number) => (
Don't do this twice. Why not just do this here and not even do the `imgUrls` array?

2024-03-15 08:39 UTC, theadley commented on src/components/homePage/latestUpdates.tsx
> +                    className=" z-10 max-h-[250px] max-w-48 overflow-hidden"
Noting this here so if I see -[250px] again I can recommend it going in your tailwind config

2024-03-15 08:39 UTC, theadley commented on src/components/homePage/latestUpdates.tsx
> +                    key={item.md_comics.md_covers[0].b2key}
Not needed as you don't loop inside this loop, only the top-level element in a loop needs a key

2024-03-15 08:39 UTC, theadley commented on src/components/homePage/seasonalComponent.tsx
> +  seasonalData: ITopTrending | undefined;
Maybe just make it optional? This point is repeated.
`seasonalData?: ITopTrending`

2024-03-15 08:39 UTC, theadley commented on src/components/homePage/seasonalComponent.tsx
> +      .filter((item) => item.content_rating === "safe")
check if the b2key also exists here

2024-03-15 08:39 UTC, theadley commented on src/components/homePage/seasonalComponent.tsx
> +  const resultingSeasonString: string = `${seasonalData.comicsByCurrentSeason.season.charAt(0).toUpperCase() + seasonalData.comicsByCurrentSeason.season.slice(1)}`;
Type is trivially inferred

2024-03-15 08:39 UTC, theadley commented on src/components/homePage/seasonalComponent.tsx
> +        {seasonalData.comicsByCurrentSeason.data
looping twice for no reason

2024-03-15 08:39 UTC, theadley commented on src/components/homePage/topTenComponent.tsx
> +          {topTenData.recentRank.slice(0, 10).map((item, index: number) => (
looping twice, only loop here, filter where the b2key actually exists

2024-03-15 08:39 UTC, theadley commented on src/components/homePage/trendingComponent.tsx
> +  const topTenTrendingData: string[] =
type is trivially inferred

2024-03-15 08:39 UTC, theadley commented on src/components/homePage/trendingComponent.tsx
> +    return <>Not Found</>;
Merge the 2 above if statements

2024-03-15 08:39 UTC, theadley commented on src/components/homePage/trendingComponent.tsx
> +    topData.trending[7].slice(0, 10).map((item) => {
loop loop loop why, do one

2024-03-15 08:39 UTC, theadley commented on tailwind.config.js
> +        allAround: "0px 0px 10px 3px rgba(255, 255, 255, 0.8)",
kebab-case ples 🙏

2024-03-15 08:39 UTC, theadley commented on src/components/homePage/trendingComponent.tsx
> +              backgroundImage: `url(${imgUrls[index]})`,
No need, we have the item already, use it's property

2024-03-15 08:39 UTC, theadley commented on src/services/format-date.ts
> +export default function formatDateToTime(date: string) {
Can we not do all of this with date-fns with formatDistanceToNow with the suffix appended and parse?

2024-03-15 08:39 UTC, theadley commented on src/services/format-date.ts
> +  const formattedTime = newdate.toLocaleString("en-US", {
So many extra variables? Why?

2024-03-15 08:39 UTC, theadley commented on src/services/format-date.ts
> +  return result + " ago";
Can this not be:
`return formatDistance(new Date(date), Date.now(), {addSuffix: true});`

2024-03-15 09:14 UTC, Hugovs2000 commented on src/components/homePage/latestUpdates.tsx
> +        <button className="text-blue-400">See more</button>
Correct

2024-03-15 09:18 UTC, Hugovs2000 commented on src/components/homePage/seasonalComponent.tsx
> +    return <>Not Found</>;
This will be looked at later, thanks for noting it though.

2024-03-15 14:28 UTC, theadley requested changes
Very nice refactor. A lot cleaner code and separation. Now to get naming right.

2024-03-15 14:28 UTC, theadley commented on src/modules/HomePage/components/ListGenres.tsx
> +function ListGenres({ genre }: { genre?: MdComicMdGenre }) {
It's a singular Genre so name accordingly please 🙏

2024-03-15 14:28 UTC, theadley commented on src/modules/HomePage/components/ListLatestUpdates.tsx
> +function ListLatestUpdates({ item }: { item: NewUpdates }) {
Name implies more than one. Type is also implying more than one. We almost never use pluralised types btw. It should be more like `NewUpdatedManga` so it's singular and you know what it is.

2024-03-15 14:28 UTC, theadley commented on src/modules/HomePage/components/ListSeasonalMangas.tsx
> +function ListSeasonalMangas({ item }: { item: Daum }) {
SeasonalManga, no plural. What is a `Daum` type? Make the typename make sense please.

2024-03-15 14:28 UTC, theadley commented on src/modules/HomePage/components/ListTopTen.tsx
> +function ListTopTen({ item, index }: { item: RecentRank; index: number }) {
Not a list. Please name accordingly.

2024-03-15 14:28 UTC, theadley commented on src/modules/HomePage/components/ListTrendingCards.tsx
> +function ListTrendingCard({
Not a list

2024-03-18 07:06 UTC, theadley requested changes
Review your types as a few of them are identical to one another.

2024-03-18 09:19 UTC, theadley approved these changes
Good soup

2024-03-18 09:51 UTC, merged