Search feature
Hugovs2000/React-Project pull request #7
Opened 2024-03-21 16:01 UTC by Hugovs2000

This PR deals with the Search Page and changes to other pages required to make the search page work. Some sketch styling took place due to ant design components being weird. Any suggested changes would be appreciated. Oh and if you were wondering, I made use of React hook forms and Yup for validation.

2024-03-22 06:07 UTC, yanevdw approved these changes
Nicely done! Looks good to me.

2024-03-22 07:18 UTC, Julianna-Venter approved these changes
Just one question on some hard coded numbers, but other than that looks good

2024-03-22 07:18 UTC, Julianna-Venter commented on src/modules/SearchPage/components/SearchForm.tsx
> +            Ongoing: 1, Completed: 2, Cancelled: 3, Hiatus: 4
Is this still mock data? is it supposed to be hard coded numbers here?

2024-03-22 10:16 UTC, Hugovs2000 commented on src/modules/SearchPage/components/SearchForm.tsx
> +            Ongoing: 1, Completed: 2, Cancelled: 3, Hiatus: 4
So this is used as "user feedback" to let them know they need to choose between those options. Only way I thought of bringing in some kind of validation.

2024-03-22 22:19 UTC, LesediMoko approved these changes
Nice use of validation and forms here! Just a comment on the labelling and error message (relating to validation)

2024-03-22 22:19 UTC, LesediMoko commented on src/modules/SearchPage/components/SearchForm.tsx
I really like the usage of validation. Maybe consider error message for the other properties like you did with the type number

2024-03-22 22:19 UTC, LesediMoko commented on src/models/SortOptions.ts
I feel like "Follow Count" and "User Follow Count" may be a bit confusing to differentiate. I know that's how it looks like in the API but try (if possible) to make the names a bit for descriptive

2024-03-23 14:48 UTC, Musa-Mabasa commented on src/modules/SearchPage/components/QueryResults.tsx
> +                manga: comic.slug!,
Avoid using assertion in this case. It is not always guaranteed that slug will never be null. Never trust the API.

2024-03-23 14:50 UTC, Musa-Mabasa commented on src/modules/SearchPage/components/SearchCard.tsx
> +    comic.md_covers?.[0].b2key && (
You can add more to this by checking the existence of the 0 index as well: `comic.md_covers?.[0]?.b2key`.

2024-03-23 14:59 UTC, Musa-Mabasa requested changes
Some safety checking changes

2024-03-25 05:32 UTC, Hugovs2000 commented on src/modules/SearchPage/components/QueryResults.tsx
> +                manga: comic.slug!,
Thanks, must've missed this one

2024-03-25 05:38 UTC, Hugovs2000 commented on src/modules/SearchPage/components/SearchCard.tsx
> +    comic.md_covers?.[0].b2key && (
Good eye. Missed it as well

2024-03-25 05:47 UTC, Hugovs2000 commented on src/models/SortOptions.ts
I am not quite sure what user follow count is so I will just make use of follow count. Thanks

2024-03-25 06:02 UTC, Hugovs2000 commented on src/models/SortOptions.ts
I meant I will make use of user_follow_count instead of follow_count as that gives the numbers I am looking for

2024-03-25 06:03 UTC, Hugovs2000 commented on src/modules/SearchPage/components/SearchForm.tsx
Not quite sure how I can do that since they cant error out on anything other than the status?

2024-03-25 09:01 UTC, Musa-Mabasa approved these changes
Nicely done, everything looks good. 👍

2024-03-25 09:07 UTC, merged