See more feature
Hugovs2000/React-Project pull request #9
Opened 2024-03-27 06:51 UTC by Hugovs2000

This PR deals with the see more page that is navigated to from the home page when a user wants to see either more seasonal mangas or latest updates.

2024-03-27 20:17 UTC, Julianna-Venter approved these changes
minor comments, one "any" that needs to be changed (yes it is auto generated, but should still be changed) Otherwise it looks good to me.

2024-03-27 20:17 UTC, Julianna-Venter commented on src/modules/SeeMorePage/components/Skeletons/SeeMoreSkeleton.tsx
> +        <div className="skeleton w-20 h-32"></div>
there are ways to do this a bit better, but they're more time consuming (which is probably unnecessary here). If it adds value for you, maybe do a loop or tailwind class of some sort. Although it's not a requirement.

2024-03-27 20:17 UTC, Julianna-Venter commented on src/routeTree.gen.ts
> +} as any)
change `any`s to `unknown`s

2024-03-28 05:46 UTC, CharelMarais requested changes
Just a few comments, please look at:
- The any's
- The redundant code that can be a loop
- Splitting TSX returns to their own comps (Single Responsibility)

2024-03-28 05:46 UTC, CharelMarais commented on src/modules/SeeMorePage/components/Skeletons/SeeMoreSkeleton.tsx
> +        <div className="skeleton w-20 h-32"></div>
I agree, definitely do this as a loop.

2024-03-28 05:46 UTC, CharelMarais commented on src/modules/SeeMorePage/SeeMorePage.tsx
> +    return (
I would suggest moving these returns into their own components and returning the element component something like `<SeeMoreLatest />` `<SeeMoreSeasonal />` `<SeeMoreNotFound />` like what you did for `<SeeMoreSkeleton />`

2024-03-28 06:25 UTC, Hugovs2000 commented on src/modules/SeeMorePage/SeeMorePage.tsx
> +    return (
I agree, will do 👍🏻

2024-03-28 06:26 UTC, Hugovs2000 commented on src/modules/SeeMorePage/components/Skeletons/SeeMoreSkeleton.tsx
> +        <div className="skeleton w-20 h-32"></div>
Cool thing 👍🏻

2024-03-28 06:27 UTC, Hugovs2000 commented on src/routeTree.gen.ts
> +} as any)
I'm not sure how to change this since the routeTree.gen.ts file regenerates itself each time I run the code?

2024-03-28 17:32 UTC, merged